"""
All sources to scrape — official sites via Firecrawl, social/discovery via Apify.
"""

# ─── OFFICIAL SOURCES (Firecrawl) ──────────────────────────────────────────────
# crawl=True → follow internal links (use for index/listing pages)
# crawl=False → single page scrape

OFFICIAL_SOURCES = [

    # ── PREREQUISITE (do these first, unlocks everything else) ──────────────
    {
        "id": "dpiit_recognition",
        "name": "DPIIT Startup Recognition",
        "url": "https://www.startupindia.gov.in/content/sih/en/ams-application.html",
        "crawl": False,
        "category": "prerequisite",
        "tags": ["recognition", "prerequisite", "tax_benefit", "dpiit"],
        "priority": 0,
    },
    {
        "id": "udyam_registration",
        "name": "Udyam Registration (MSME)",
        "url": "https://udyamregistration.gov.in/",
        "crawl": False,
        "category": "prerequisite",
        "tags": ["msme", "prerequisite", "udyam"],
        "priority": 0,
    },

    # ── CENTRAL GOVERNMENT ──────────────────────────────────────────────────
    {
        "id": "pmfme",
        "name": "PMFME — PM Formalisation of Micro Food Processing",
        "url": "https://pmfme.mofpi.gov.in/pmfme/",
        "crawl": True,
        "category": "central_gov",
        "tags": ["food", "manufacturing", "grant", "subsidy", "mofpi"],
        "priority": 1,
    },
    {
        "id": "mofpi_pli",
        "name": "MOFPI PLI Scheme for Food Processing",
        "url": "https://mofpi.gov.in/schemes/pli-scheme-food-processing-industry",
        "crawl": False,
        "category": "central_gov",
        "tags": ["food", "pli", "manufacturing", "central"],
        "priority": 1,
    },
    {
        "id": "mofpi_all_schemes",
        "name": "MOFPI — All Schemes",
        "url": "https://mofpi.gov.in/schemes",
        "crawl": True,
        "category": "central_gov",
        "tags": ["food", "processing", "central"],
        "priority": 1,
    },
    {
        "id": "sisfs",
        "name": "Startup India Seed Fund Scheme (SISFS)",
        "url": "https://seedfund.startupindia.gov.in/",
        "crawl": True,
        "category": "central_gov",
        "tags": ["seed_fund", "startup", "grant", "equity"],
        "priority": 1,
    },
    {
        "id": "startup_india_schemes",
        "name": "Startup India — All Government Schemes",
        "url": "https://www.startupindia.gov.in/content/sih/en/government-schemes.html",
        "crawl": False,
        "category": "central_gov",
        "tags": ["startup", "schemes", "central"],
        "priority": 1,
    },
    {
        "id": "msme_schemes",
        "name": "MSME Ministry — All Schemes",
        "url": "https://msme.gov.in/schemes",
        "crawl": True,
        "category": "central_gov",
        "tags": ["msme", "grant", "subsidy", "loan"],
        "priority": 1,
    },
    {
        "id": "nabard_food",
        "name": "NABARD — Food & Agro Processing",
        "url": "https://www.nabard.org/content.aspx?id=591",
        "crawl": False,
        "category": "central_gov",
        "tags": ["food", "agro", "loan", "nabard"],
        "priority": 2,
    },
    {
        "id": "birac_big",
        "name": "BIRAC — Biotechnology Ignition Grant (BIG)",
        "url": "https://birac.nic.in/scheme_detail.php?id=14",
        "crawl": False,
        "category": "central_gov",
        "tags": ["biotech", "food_tech", "grant", "50L"],
        "priority": 2,
    },
    {
        "id": "birac_all",
        "name": "BIRAC — All Schemes",
        "url": "https://birac.nic.in/scheme.php",
        "crawl": False,
        "category": "central_gov",
        "tags": ["biotech", "food_tech", "grant"],
        "priority": 2,
    },
    {
        "id": "aim_programs",
        "name": "Atal Innovation Mission — Programs",
        "url": "https://aim.gov.in/programs.php",
        "crawl": False,
        "category": "central_gov",
        "tags": ["innovation", "student", "grant", "atal"],
        "priority": 2,
    },
    {
        "id": "sidbi_startup",
        "name": "SIDBI — Startup Mitra & Schemes",
        "url": "https://www.sidbi.in/en/products-and-services/startup-ecosystem",
        "crawl": False,
        "category": "central_gov",
        "tags": ["loan", "startup", "sidbi", "debt"],
        "priority": 2,
    },
    {
        "id": "nif",
        "name": "National Innovation Foundation",
        "url": "https://nif.org.in/",
        "crawl": False,
        "category": "central_gov",
        "tags": ["innovation", "grant", "grassroots"],
        "priority": 3,
    },
    {
        "id": "dst_nstedb",
        "name": "DST — NSTEDB Technology Business Incubators",
        "url": "https://nstedb.com/",
        "crawl": False,
        "category": "central_gov",
        "tags": ["dst", "incubation", "technology"],
        "priority": 2,
    },
    {
        "id": "fssai_schemes",
        "name": "FSSAI — FoSTaC & FOSCOS",
        "url": "https://foscos.fssai.gov.in/",
        "crawl": False,
        "category": "central_gov",
        "tags": ["fssai", "food_safety", "compliance", "prerequisite"],
        "priority": 1,
    },

    # ── TELANGANA STATE ─────────────────────────────────────────────────────
    {
        "id": "thub",
        "name": "T-Hub Hyderabad — Programs & Cohorts",
        "url": "https://t-hub.co/programs",
        "crawl": True,
        "category": "state_incubator",
        "tags": ["hyderabad", "telangana", "incubation", "equity"],
        "priority": 1,
    },
    {
        "id": "telangana_startup_policy",
        "name": "Telangana Startup Policy",
        "url": "https://startup.telangana.gov.in/",
        "crawl": True,
        "category": "state_gov",
        "tags": ["telangana", "hyderabad", "startup", "grant", "subsidy"],
        "priority": 1,
    },
    {
        "id": "wehub",
        "name": "WE Hub Telangana — Programs",
        "url": "https://www.wehub.telangana.gov.in/",
        "crawl": False,
        "category": "state_gov",
        "tags": ["telangana", "women", "incubation", "grant"],
        "priority": 2,
    },
    {
        "id": "tsic",
        "name": "TSIC — Telangana State Innovation Cell",
        "url": "https://tsic.telangana.gov.in/",
        "crawl": False,
        "category": "state_gov",
        "tags": ["telangana", "innovation", "grant"],
        "priority": 2,
    },

    # ── RAJASTHAN STATE ─────────────────────────────────────────────────────
    {
        "id": "istart_rajasthan",
        "name": "iStart Rajasthan — Startup Scheme",
        "url": "https://istart.rajasthan.gov.in/",
        "crawl": True,
        "category": "state_gov",
        "tags": ["rajasthan", "pilani", "startup", "grant", "subsidy"],
        "priority": 1,
    },
    {
        "id": "rajasthan_msme_policy",
        "name": "Rajasthan MSME & Industries Policy",
        "url": "https://industries.rajasthan.gov.in/",
        "crawl": False,
        "category": "state_gov",
        "tags": ["rajasthan", "msme", "manufacturing", "subsidy"],
        "priority": 2,
    },

    # ── BITS PILANI ─────────────────────────────────────────────────────────
    {
        "id": "bits_tbi",
        "name": "BITS Pilani Technology Business Incubator (TBI)",
        "url": "https://www.bits-pilani.ac.in/pilani/central-facilities-at-pilani/technology-business-incubator/",
        "crawl": False,
        "category": "university",
        "tags": ["bits", "incubation", "student", "pilani"],
        "priority": 1,
    },
    {
        "id": "pieds",
        "name": "PIEDS — BITS Pilani Entrepreneurship Society",
        "url": "https://pieds.bits-pilani.ac.in/",
        "crawl": False,
        "category": "university",
        "tags": ["bits", "student", "mentorship", "network"],
        "priority": 1,
    },

    # ── INCUBATORS & ACCELERATORS ───────────────────────────────────────────
    {
        "id": "nsrcel",
        "name": "NSRCEL — IIM Bangalore",
        "url": "https://nsrcel.iimb.ac.in/programs/",
        "crawl": True,
        "category": "incubator",
        "tags": ["incubation", "iim", "grant", "fmcg"],
        "priority": 2,
    },
    {
        "id": "ciie",
        "name": "CIIE.CO — IIM Ahmedabad",
        "url": "https://ciie.co/programs/",
        "crawl": False,
        "category": "incubator",
        "tags": ["incubation", "iim", "food", "fmcg"],
        "priority": 2,
    },
    {
        "id": "niftem",
        "name": "NIFTEM — Food Tech Incubation Center",
        "url": "https://niftem-k.ac.in/tbi/",
        "crawl": False,
        "category": "incubator",
        "tags": ["food_tech", "incubation", "grant", "niftem"],
        "priority": 1,
    },
    {
        "id": "agri_udaan",
        "name": "Agri Udaan — NAIF Agrifood Accelerator",
        "url": "https://naif.in/agri-udaan/",
        "crawl": False,
        "category": "accelerator",
        "tags": ["food", "agri", "accelerator", "equity"],
        "priority": 2,
    },
    {
        "id": "villgro",
        "name": "Villgro Innovation Foundation",
        "url": "https://villgro.org/programs/",
        "crawl": False,
        "category": "incubator",
        "tags": ["social_impact", "food", "health", "grant"],
        "priority": 2,
    },
    {
        "id": "nasscom_10k",
        "name": "NASSCOM 10K Startups",
        "url": "https://nasscom.in/10000startups/",
        "crawl": False,
        "category": "accelerator",
        "tags": ["startup", "mentorship", "network"],
        "priority": 3,
    },
    {
        "id": "india_accelerator",
        "name": "India Accelerator",
        "url": "https://indiaaccelerator.co/program/",
        "crawl": False,
        "category": "accelerator",
        "tags": ["accelerator", "equity", "mentorship"],
        "priority": 3,
    },

    # ── INVESTORS (equity but worth knowing) ────────────────────────────────
    {
        "id": "100x_vc",
        "name": "100X.VC — Apply",
        "url": "https://100x.vc/apply/",
        "crawl": False,
        "category": "investor",
        "tags": ["equity", "seed", "india"],
        "priority": 3,
    },
    {
        "id": "antler_india",
        "name": "Antler India",
        "url": "https://www.antler.co/location/india",
        "crawl": False,
        "category": "investor",
        "tags": ["equity", "pre_seed", "founder"],
        "priority": 3,
    },
    {
        "id": "sequoia_surge",
        "name": "Peak XV (Sequoia) Surge",
        "url": "https://www.surgeahead.com/",
        "crawl": False,
        "category": "investor",
        "tags": ["equity", "seed", "accelerator"],
        "priority": 3,
    },

    # ── CORPORATE / CLOUD CREDITS ────────────────────────────────────────────
    {
        "id": "google_startups",
        "name": "Google for Startups India",
        "url": "https://startup.google.com/intl/en_in/",
        "crawl": False,
        "category": "corporate",
        "tags": ["cloud_credits", "mentorship", "google"],
        "priority": 3,
    },
    {
        "id": "aws_activate",
        "name": "AWS Activate for Startups",
        "url": "https://aws.amazon.com/startups/start-building/",
        "crawl": False,
        "category": "corporate",
        "tags": ["cloud_credits", "aws"],
        "priority": 3,
    },
    {
        "id": "microsoft_founders",
        "name": "Microsoft for Startups Founders Hub",
        "url": "https://www.microsoft.com/en-us/startups",
        "crawl": False,
        "category": "corporate",
        "tags": ["cloud_credits", "azure", "microsoft"],
        "priority": 3,
    },
]


# ─── GOOGLE SEARCH QUERIES (Apify Discovery) ──────────────────────────────────
GOOGLE_QUERIES = [
    "India food startup grant 2025 how to apply",
    "startup grant Hyderabad Telangana food processing 2025",
    "Rajasthan startup grant scheme food manufacturing 2025",
    "BITS Pilani student startup funding incubator 2025",
    "India FMCG food startup seed fund apply",
    "MSME food processing startup India subsidy 2025",
    "student startup India DPIIT recognition how to get",
    "India startup competition food FMCG prize 2025",
    "India food tech incubator apply 2025 open",
    "sous vide RTE food startup India grant",
    "protein food startup India funding scheme",
    "T-Hub Hyderabad cohort 2025 application process",
    "iStart Rajasthan startup scheme how to apply",
    "PMFME scheme apply food processing startup India",
    "Telangana startup policy incentives food company",
    "NASSCOM food startup accelerator program India",
    "India startup grant free money non-dilutive 2025",
    "CIIE IIM Ahmedabad food FMCG startup incubation",
    "NIFTEM incubation apply food tech startup",
    "India government scheme food startup pre-revenue",
]


# ─── REDDIT SOURCES (Apify) ────────────────────────────────────────────────────
REDDIT_SOURCES = {
    "subreddits": [
        "indianstartups",
        "india",
        "hyderabad",
        "Entrepreneur",
        "IndiaInvestments",
        "BITS",
    ],
    "search_queries": [
        "startup grants India food 2025",
        "BITS Pilani startup incubator experience",
        "Telangana startup scheme experience",
        "iStart Rajasthan experience review",
        "Startup India seed fund SISFS experience",
        "T-Hub selection process insider",
        "DPIIT recognition how to get approved fast",
        "PMFME scheme application tips",
        "food startup India funding journey",
        "government grant startup India non-dilutive",
        "India incubator worth it experience",
    ],
}


# ─── TWITTER/X SEARCH QUERIES (Apify) ─────────────────────────────────────────
TWITTER_QUERIES = [
    "#StartupIndia grants food",
    "food startup grant India 2025",
    "MOFPI scheme food processing startup",
    "T-Hub cohort 2025 applications open",
    "iStart Rajasthan 2025",
    "BITS Pilani startup funding",
    "Telangana startup incubator 2025",
    "India food tech startup grant",
    "#PMFME scheme apply",
    "startup seed fund India non-dilutive",
]
